# maintainer: u1and0 <e01.ando60@gmail.com>
# version 3.7 for docker version 18.06+
# see https://docs.docker.com/compose/compose-file/
# What for:
#    docker in docker dev.env
#
#    * master: zsh & zplug env. Parents for all docker image.
#    * jupyter: python env. It can use ipython & jupyter
#    * go: golang env.
#
# Usage:
#	 $ cd /path/to/notecompose
#    $ docker-compose up
#    $ docker exec -it notecompose_master_1 zsh -l
#
# 	 # Login master container then...
#    $ tmux
#
#    # Login go env
#    $ docker exec -it notecompose_go_1 zsh -l
#
#    # Login python env
# 	 $ docker exec -it notecompose_jupyter_1 bash -c ". .bashrc && zsh"
#
#    # Login python env as ipython
# 	 $ docker exec -it notecompose_jupyter_1 bash -c ". .bashrc && ipython"
#
#    # Setup git after login
#    $ git stash
#    $ git fetch
#    $ git checkout origin/develop
#    $ git switch -c develop
#    $ git stash pop
#       for shortly
#    $ gst && g fetch && gch origin/develop && g switch -c develop && gst pop
#
#    # Setup pacman after login
#    $ pacman -Sy archlinux-keyring
#    $ pacman -Syu
version: '3'
services:

    master:
        image: "u1and0/docker:latest"
        tty: true
        volumes:
            - "/home/u1and0:/home/u1and0/home"
            - "/home/u1and0/Dropbox:/home/u1and0/Dropbox"
            - "/home/u1and0/.zsh_history:/home/u1and0/.zsh_history"
            - "/home/u1and0/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
            - "/var/run/docker.sock:/var/run/docker.sock"
        restart: "always"
        environment:
            - "HOST=master"
        ports:
            - "8000:8000"

    python:
        # jupyter tagはpasswordを設定したイメージ
        # [Jupyter on Dockerでパスワードの設定方法が分からないあなたへ](https://qiita.com/Yusuke-Shimizu/items/731ca71b3c4c3649ec7f)
        image: "u1and0/python:latest"
        volumes:
            - "/home/u1and0:/home/u1and0/home"
            - "/home/u1and0/Dropbox:/home/u1and0/Dropbox"
            - "/home/u1and0/.zsh_history:/home/u1and0/.zsh_history"
            - "/home/u1and0/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
        environment:
            - "PYTHONPATH=/home/u1and0/Dropbox/Program/python"
            - "HOST=python"
        command: ["bash", "-c", "source /etc/profile.d/conda.sh && conda activate && jupyter lab"]
        ports:
            - "8888:8888"  # jupyter notebook
            - "8880:8880"  # plotly dash

    go:
        image: "u1and0/go:latest"
        tty: true
        volumes:
            - "/home/u1and0:/home/u1and0/home"
            - "/home/u1and0/Dropbox:/home/u1and0/Dropbox"
            - "/home/u1and0/.zsh_history:/home/u1and0/.zsh_history"
            - "/home/u1and0/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
        environment:
            - "HOST=go"
            # - "GOPATH=/home/u1and0/go"
        working_dir: "$GOPATH"
        ports:
            - "8080:8080"
            - "9000:9000"
        cap_add:
            - "SYS_PTRACE" # for golang debugger

    # rust:
    #     image: "u1and0/rust:latest"
    #     tty: true
    #     volumes:
    #         - "/home/u1and0:/home/u1and0/home"
    #         - "/home/u1and0/Dropbox:/home/u1and0/Dropbox"
    #         - "/home/u1and0/.zsh_history:/home/u1and0/.zsh_history"
    #         - "/home/u1and0/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
    #     environment:
    #         - "HOST=rust"
    #     ports:
    #         - "8089:8089"

    # nim:
    #     image: "u1and0/nim:latest"
    #     tty: true
    #     volumes:
    #         - "/home/u1and0:/home/u1and0/home"
    #         - "/home/u1and0/Dropbox:/home/u1and0/Dropbox"
    #         - "/home/u1and0/.zsh_history:/home/u1and0/.zsh_history"
    #         - "/home/u1and0/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
    #     environment:
    #         - "HOST=nim"
    #     ports:
    #         - "0.0.0.0:3333:3333"

    deno:
        image: u1and0/deno:latest
        tty: true
        volumes:
            - "/home/u1and0:/home/u1and0/home"
            - "/home/u1and0/Dropbox:/home/u1and0/Dropbox"
            - "/home/u1and0/.zsh_history:/home/u1and0/.zsh_history"
            - "/home/u1and0/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
        environment:
            - "HOST=deno"
        ports:
            - "3000:3000"

