name: Weekly Docker Build

on:
  workflow_dispatch:  # 手動ビルド
  # schedule:
  #   - cron: '0 9 * * 0'  # Run every Sunday at 9:00 AM
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get GitHub SHA
        id: get_sha
        run: echo "::set-output name=SHA::$(git rev-parse --short HEAD)"
      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker_archlinux_env
          # file: ./docker_archlinux_env/Dockerfile
          push: true
          tags: |
            u1and0/archlinux:latest
            u1and0/archlinux:${{ steps.get_sha.outputs.SHA }}
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
