name: Weekly Docker Build

on:
  # 手動ビルド
  workflow_dispatch:
  # mainにpushされたとき
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '*.yml'
    branches:
      - main
  # Run every Sunday at 9:00 AM
  schedule:
    - cron: '0 9 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        context: ["docker", "go", "deno", "python"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get GitHub SHA
        id: get_sha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push images
      #
      # yay - archlinux - neovim - zplug は継承関係があるので
      # 直列で実行する。
      - name: Build and Push yay Image
        id: build_yay
        uses: docker/build-push-action@v5
        with:
          context: ./images/yay
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            u1and0/yay:latest
            u1and0/yay:${{ steps.get_sha.outputs.SHA }}
      - name: Image Digest
        run: echo ${{ steps.build_yay.outputs.digest }}

      - name: Build and Push Archlinux Image
        id: build_archlinux
        uses: docker/build-push-action@v5
        with:
          context: ./images/archlinux
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            u1and0/archlinux:latest
            u1and0/archlinux:${{ steps.get_sha.outputs.SHA }}
      - name: Image Digest
        run: echo ${{ steps.build_archlinux.outputs.digest }}

      - name: Build and Push Neovim Image
        id: build_neovim
        uses: docker/build-push-action@v5
        with:
          context: ./images/neovim
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            u1and0/neovim:latest
            u1and0/neovim:${{ steps.get_sha.outputs.SHA }}
      - name: Image Digest
        run: echo ${{ steps.build_neovim.outputs.digest }}

      - name: Build and Push Zplug Image
        id: build_zplug
        uses: docker/build-push-action@v5
        with:
          context: ./images/zplug
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            u1and0/zplug:latest
            u1and0/zplug:${{ steps.get_sha.outputs.SHA }}
      - name: Image Digest
        run: echo ${{ steps.build_zplug.outputs.digest }}

      # docker, go, deno, python はzplugを継承しているので
      # 並列に実行できる。
      - name: Build and Push Docker in Docker, Go, Deno, Python Image
        id: build_from_zplug
        uses: docker/build-push-action@v5
        with:
          context: ./images/${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            u1and0/${{ matrix.context }}:latest
            u1and0/${{ matrix.context }}:${{ steps.get_sha.outputs.SHA }}
      - name: Image Digest
        run: echo ${{ steps.build_from_zplug.outputs.digest }}

      # PythonコンテナのときだけNimをビルド
      - name: Build and Push Nim Image
        if: matrix.context == 'python'
        id: build_nim
        uses: docker/build-push-action@v5
        with:
          context: ./images/nim
          platforms: linux/amd64
          push: true
          tags: |
            u1and0/nim:latest
            u1and0/nim:${{ steps.get_sha.outputs.SHA }}
      - name: Image Digest
        if: matrix.context == 'python'
        run: echo ${{ steps.build_nim.outputs.digest }}
